name: CloudCampusIQ-MERN-Azure

on: 
  push:
    branches: [ main ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  NODE_VERSION: '24'
  APP_NAME: cciq-mern-app

jobs:
  build_and_deploy: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      
      - name: Install FRONTEND # dependencies
        working-directory: ./client
        run: npm ci

      - name: Build FRONTEND
        working-directory: ./client
        run: npm run build

      - name: Install BACKEND # dependencies
        working-directory: ./server
        run: npm ci

      - name: prepare-to-deploy
        run: |
          mkdir deploy
          cp -R server/* deploy/
          cp -R client/dist deploy/dist
         
      - name: deploy
        uses: azure/webapps-deploy@v3
        with: 
            app-name: ${{ env.APP_NAME }} 
            publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
            package: deploy   
